CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    CELULAR VARCHAR2(10) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL UNIQUE,
    NSS VARCHAR2(11) NOT NULL UNIQUE,
    CURP VARCHAR2(18) NOT NULL UNIQUE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CLIENTE_ID
BEFORE INSERT ON CLIENTE
FOR EACH ROW
WHEN (NEW.ID_CLIENTE IS NULL)
BEGIN
    SELECT SEQ_CLIENTE.NEXTVAL
    INTO :NEW.ID_CLIENTE
    FROM DUAL;
END;
/

INSERT INTO CLIENTE (NOMBRE, FECHA_NACIMIENTO, CELULAR, CORREO, NSS, CURP)
VALUES ('Juan Perez', TO_DATE('1995-05-10','YYYY-MM-DD'),
'5512345678','juan@email.com','12345678901','PEPJ950510HDFRRN09');

COMMIT;

SELECT * FROM CLIENTE;